### PR TITLE
xDNN Matlab Classifier

### PR DESCRIPTION
**Pull request by aniruddh-1**
Please review this pull request of work on xDNN Matlab Classifier for CT Scan Detection which is contributed by me and mate Nitin Mane.

### CODE REVIEW

**Comment by AdamMiltonBarker** [comment]
Thank you @aniruddh-1 myself and @rishabhbanga will do the review ASAP.

**Review by rishabhbanga — CHANGES_REQUESTED** [review]
Step 6 is unclear for those who are installing it for the first time. You need to mention which specific to install. I selected Deep Learning for now.

Manually Installing Required Python Libraries is also unclear, since you never mentioned what matlabroot path is and/or how to get it. Don't blatantly copy sentences. Mention how to install python and then proceed with informing them of the dependencies to be installed.

**Comment by rishabhbanga** [comment]
Moreover, some of the dependencies didn't get installed. I received this error while installing all before pillow - Couldn't find a version that satisfies the requirement. Checking why this issue came up

**Comment by aniruddh-1** [comment]
Thanks Rishabh for reviewing this, sorry for copying some of the installation guides from matlab and not understanding them carefully. I have edited the installation.md as follows:
1. Step 6 edited and I focused it to choose Deep Learning package.
2. explained the matlabroot folder for installing matlab engine api.
3. I figured out the error was due to that python comes with already installed sys, os , glob, re libraries as default while
    installing the python installation package and manually installing them shows the error:
https://stackoverflow.com/questions/32302379/could-not-find-a-version-that-satisfies-the-requirement-package
    
    So I have removed those which were giving error and edited it to install those which are not available.

If you still find something is wrong, please tell, will be happy to correct the project.

**Comment by rishabhbanga** [comment]
@aniruddh-1 

-> Why is the entire MATLAB directory inside a folder by the name of 1?

-> In Installation.md it's mentioned - You will find the configuration file in the project 2 root directory. 
This is a bit unclear. What is Project 2?

-> In README.md Under Real World Testing, you've mentioned - To test an Image, navigate to the project root and exectute the following command:

Spelling would be execute, also navigate where? MATLAB or Powershell/Command Prompt? Now I did run it in both so I know it's the latter. But even there on running python3 Server.py, no messages are displayed as you've mentioned. I even checked http://127.0.0.1:5000 and it says it's unreachable

**Comment by aniruddh-1** [comment]
hey @rishabhbanga here are updates for above demanded changes:
1. The entire matlab directory is in 1 because it was said by @AdamMiltonBarker, to keep the structure of projects in numbers as there may be chances in future that we have a new project in matlab with xDNN model.
2. Sorry, I have corrected it to 1, it was mistakenly written by me.
3. I have updated the README file with saying running the command in command prompt. I am able to run the command and it shows me this message: 

Screenshot (95)

**Comment by rishabhbanga** [comment]
Strange, it doesn't work for me. I'll retrace all the steps again

**Comment by aniruddh-1** [comment]
hey rishabh, it is possible that python isn't on your path, you can check this same issue on stack:

https://stackoverflow.com/questions/61556075/python-script-wont-run-from-the-command-line-it-shows-no-error

**Pull request merged**
